"""Export the integer network for the RTL (M4/M5) and generate golden test vectors.

Run from project root:  .venv/bin/python software/ai/quantization/export_rtl.py

Writes (tracked in git, tiny):   hardware/rtl/weights/{weights,bias,mult}_L{1..4}.mem, network_params.vh, README.md
Writes (NOT in git, regenerable): data/golden/<tile>.npz, <tile>_{in,L1,L2,L3,L4,out}.hex

File formats (all text, one value per line, readable by Verilog $readmemh):
  weights_Ln.mem : int8 as 2 hex digits (two's complement), order [co][ci][ky][kx] (ky slowest of the two taps), C order.
                   Depthwise L2: [c][0][ky][kx] -> 16*9 = 144 lines.
  bias_Ln.mem    : int32 as 8 hex digits (two's complement), one per output channel.
  mult_Ln.mem    : requant multiplier M, unsigned 16 bit as 4 hex digits, one per output channel.
  network_params.vh : SHIFT per layer and the layer geometry as `localparam`s.
Golden hex files: one byte (2 hex digits) per line, order [y][x][c] with c fastest, i.e. pixel-major with channel 0 first.
  <tile>_in.hex  : (h+6) x (w+6) x 3 uint8 tile WITH halo    <tile>_Ln.hex : output of layer n (uint8)    <tile>_out.hex : 2h x 2w x 3
"""
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "software" / "ai"))
from dataset.pairs import list_images, load_rgb, make_pair  # noqa: E402
from quantization.integer_reference import LAYER_SPEC, QNet, forward_layers, pad_replicate  # noqa: E402

QPARAMS = ROOT / "software/ai/quantization/qparams.npz"
WDIR = ROOT / "hardware" / "rtl" / "weights"
GDIR = ROOT / "data" / "golden"

README = """# Exported network parameters (generated by `software/ai/quantization/export_rtl.py` - do not edit by hand)

Network: L1 conv3x3 3->16 | L2 depthwise3x3 16 | L3 conv1x1 16->16 | L4 conv3x3 16->12 (+ pixel shuffle, no maths).
Per output value: `acc = bias + sum(act_uint8 * w_int8)`, `y = clamp((acc*M + 2^(SHIFT-1)) >> SHIFT, 0, 255)` (arithmetic shift).
Every output channel of a layer has its own M (16-bit unsigned); SHIFT is one value per layer (see `network_params.vh`).
Accumulator fits signed 32 bit; the product `acc*M` needs up to ~40 bits (checked in `test_integer.py`).

| File | Format | Order |
|---|---|---|
| `weights_Ln.mem` | int8, 2 hex digits, two's complement | `[co][ci][ky][kx]`, C order (L2: `[c][0][ky][kx]`) |
| `bias_Ln.mem` | int32, 8 hex digits, two's complement | `[co]` |
| `mult_Ln.mem` | uint16, 4 hex digits | `[co]` |

Line counts: L1 432 weights / 16 bias, L2 144 / 16, L3 256 / 16, L4 1728 / 12.
`ky` = vertical tap (0 = row above the output pixel), `kx` = horizontal tap; output(y,x) uses input(y+ky, x+kx) (VALID, no padding).
Pixel shuffle: high-res pixel (2y+dy, 2x+dx), colour c = L4 channel 4c + 2dy + dx at (y,x).
"""


def hex_lines(arr, digits):
    mask = (1 << (4 * digits)) - 1
    return "\n".join(f"{int(v) & mask:0{digits}x}" for v in arr.flatten()) + "\n"


def export_weights(net):
    WDIR.mkdir(parents=True, exist_ok=True)
    vh = ["// generated by export_rtl.py - do not edit"]
    for L, (name, cin, cout, k, dw) in zip(net.layers, LAYER_SPEC):
        n = name[1]
        (WDIR / f"weights_L{n}.mem").write_text(hex_lines(L["w"], 2))
        (WDIR / f"bias_L{n}.mem").write_text(hex_lines(L["b"], 8))
        (WDIR / f"mult_L{n}.mem").write_text(hex_lines(L["m"], 4))
        vh += [f"localparam L{n}_CIN = {cin};", f"localparam L{n}_COUT = {cout};", f"localparam L{n}_K = {k};",
               f"localparam L{n}_DEPTHWISE = {int(dw)};", f"localparam L{n}_SHIFT = {L['shift']};"]
    (WDIR / "network_params.vh").write_text("\n".join(vh) + "\n")
    (WDIR / "README.md").write_text(README)


def golden_tiles():
    """(name, tile uint8 (h+6, w+6, 3)) list: stress tiles plus real image tiles (when the training images are present)."""
    rng = np.random.default_rng(1234)
    tiles = [("zeros", np.zeros((70, 70, 3), np.uint8)), ("full255", np.full((70, 70, 3), 255, np.uint8)),
             ("noise", rng.integers(0, 256, (70, 70, 3)).astype(np.uint8))]
    px = np.zeros((70, 70, 3), np.uint8)
    px[35, 35] = (255, 128, 0)
    tiles.append(("pixel", px))
    ramp = np.zeros((70, 70, 3), np.uint8)
    ramp[..., 0] = np.linspace(0, 255, 70).astype(np.uint8)[None, :]
    ramp[..., 1] = np.linspace(255, 0, 70).astype(np.uint8)[:, None]
    ramp[..., 2] = 255 * ((np.add.outer(np.arange(70), np.arange(70)) // 5) % 2)
    tiles.append(("ramp", ramp))
    tiles.append(("small12", rng.integers(0, 256, (12, 12, 3)).astype(np.uint8)))  # 6x6 core -> 12x12 output, quick RTL smoke test
    train = list_images(ROOT / "data" / "train" / "HR")[:3]
    for i, p in enumerate(train):
        lr, _ = make_pair(load_rgb(p), 2)
        y, x = int(rng.integers(0, lr.shape[0] - 70)), int(rng.integers(0, lr.shape[1] - 70))
        tiles.append((f"real{i}", lr[y:y + 70, x:x + 70].copy()))
        if i == 0:
            tiles.append(("real_corner", pad_replicate(lr)[:70, :70].copy()))  # top-left border tile, replicate-padded halo
    return tiles


def export_golden(net):
    GDIR.mkdir(parents=True, exist_ok=True)
    for name, tile in golden_tiles():
        layers = forward_layers(net, tile.transpose(2, 0, 1).copy())
        out = layers[-1].astype(np.uint8).transpose(1, 2, 0)
        hwc = [lay.astype(np.uint8).transpose(1, 2, 0) for lay in layers[:4]]
        np.savez(GDIR / f"{name}.npz", tile=tile, L1=layers[0], L2=layers[1], L3=layers[2], L4=layers[3], out=out)
        (GDIR / f"{name}_in.hex").write_text(hex_lines(tile, 2))
        for i, a in enumerate(hwc, 1):
            (GDIR / f"{name}_L{i}.hex").write_text(hex_lines(a, 2))
        (GDIR / f"{name}_out.hex").write_text(hex_lines(out, 2))
        print(f"golden {name}: in {tile.shape} -> out {out.shape}")


if __name__ == "__main__":
    net = QNet.load(QPARAMS)
    export_weights(net)
    print("wrote", WDIR.relative_to(ROOT))
    export_golden(net)
